In [ ]:
 # Loading packages requiresd for the Feed Forward Neural 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import classification_report

Using TensorFlow backend.


In [ ]:
# Loading the training and test Dataset
train_dataset = pd.read_csv('train.csv')
test_dataset = pd.read_csv('test.csv')

In [ ]:
train_dataset.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject  Activity
0           0.288585          -0.020294  ...        1  STANDING
1           0.278419          -0.016411  ...        1  STANDING
2           0.279653          -0.019467  ...        1  STANDING
3           0.279174          -0.026201  ...        1  STANDING
4           0.276629          -0.016570  ...        1  STANDING

[5 rows x 563 columns]

In [ ]:
train_dataset.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  angle(Z,gravityMean)      subject
count        7352.000000        7352.000000  ...           7352.000000  7352.000000
mean            0.274488          -0.017695  ...             -0.056515    17.413085
std             0.070261           0.040811  ...              0.279122     8.975143
min            -1.000000          -1.000000  ...             -1.000000     1.000000
25%             0.262975          -0.024863  ...             -0.143414     8.000000
50%             0.277193          -0.017219  ...              0.003181    19.000000
75%             0.288461          -0.010783  ...              0.107659    26.000000
max             1.000000           1.000000  ...              1.000000    30.000000

[8 rows x 562 columns]

In [ ]:
train_dataset.shape

(7352, 563)

In [ ]:
test_dataset.shape

(2947, 563)

In [ ]:
train_dataset["Activity"].unique()

array(['STANDING', 'SITTING', 'LAYING', 'WALKING', 'WALKING_DOWNSTAIRS',
       'WALKING_UPSTAIRS'], dtype=object)

In [ ]:
test_dataset["Activity"].unique()

array(['STANDING', 'SITTING', 'LAYING', 'WALKING', 'WALKING_DOWNSTAIRS',
       'WALKING_UPSTAIRS'], dtype=object)

In [ ]:
train_dataset['Activity'] = train_dataset['Activity'].map({"STANDING": 0, "SITTING": 1, "LAYING": 2, "WALKING": 3, "WALKING_DOWNSTAIRS": 4, "WALKING_UPSTAIRS": 5})

In [ ]:
test_dataset['Activity'] = test_dataset['Activity'].map({"STANDING": 0, "SITTING": 1, "LAYING": 2, "WALKING": 3, "WALKING_DOWNSTAIRS": 4, "WALKING_UPSTAIRS": 5})

In [ ]:
train_dataset['Activity'].value_counts()

2    1407
0    1374
1    1286
3    1226
5    1073
4     986
Name: Activity, dtype: int64

In [ ]:
test_dataset['Activity'].value_counts()

2    537
0    532
3    496
1    491
5    471
4    420
Name: Activity, dtype: int64

In [ ]:
features_cols = set(train_dataset.columns)
features_cols.remove('Activity')

In [ ]:
print(features_cols)

{'tBodyAccMag-iqr()', 'tBodyGyroJerkMag-energy()', 'fBodyAccJerk-mean()-Z', 'fBodyAccJerk-meanFreq()-X', 'fBodyGyro-maxInds-X', 'tGravityAccMag-arCoeff()1', 'tBodyGyro-max()-Z', 'tBodyAcc-entropy()-X', 'tBodyAccJerk-energy()-Z', 'fBodyGyro-bandsEnergy()-1,8.2', 'fBodyAcc-skewness()-Z', 'fBodyGyro-bandsEnergy()-1,16.1', 'tGravityAcc-sma()', 'tBodyGyro-mean()-Y', 'tBodyAccJerk-std()-Y', 'fBodyGyro-bandsEnergy()-25,48.2', 'tBodyAcc-arCoeff()-Y,1', 'tBodyAcc-arCoeff()-Z,2', 'fBodyAccJerk-mean()-X', 'fBodyAccMag-mad()', 'tBodyGyroJerkMag-arCoeff()4', 'tBodyGyro-arCoeff()-Y,3', 'fBodyAccJerk-kurtosis()-Y', 'tBodyAcc-max()-Z', 'tGravityAcc-correlation()-X,Z', 'fBodyAcc-bandsEnergy()-57,64', 'fBodyBodyGyroJerkMag-kurtosis()', 'tBodyGyroMag-iqr()', 'fBodyAccMag-iqr()', 'fBodyAcc-bandsEnergy()-41,48.2', 'fBodyGyro-energy()-Y', 'fBodyGyro-maxInds-Y', 'tBodyAcc-mean()-Y', 'tBodyGyro-min()-Z', 'fBodyBodyGyroJerkMag-skewness()', 'fBodyGyro-bandsEnergy()-57,64.2', 'tBodyGyroJerkMag-arCoeff()2', 'tBod

In [ ]:
Label_cols = ['Activity']

In [ ]:
# Training Set
X_train = train_dataset.loc[:, features_cols].values
y_train = train_dataset.loc[:, Label_cols].values

In [ ]:
X_train

array([[-0.9576374 , -0.99994898, -0.98969609, ..., -0.43647104,
        -0.97297139, -0.99673689],
       [-0.98124826, -0.99996983, -0.98973975, ..., -0.12204037,
        -0.06494907, -0.99742453],
       [-0.9857669 , -0.99995494, -0.98756628, ..., -0.61872514,
        -0.12787926, -0.99516317],
       ...,
       [-0.41652756, -0.93160987, -0.6208069 , ..., -0.03029946,
         0.48480638, -0.48265674],
       [-0.51661345, -0.9379116 , -0.67096899, ..., -0.093485  ,
         0.76785653, -0.49813113],
       [-0.51773817, -0.94785117, -0.68493786, ..., -0.57275746,
         0.67261926, -0.47810419]])

In [ ]:
y_train[9:40]
        

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
# Convert y_train digits into one hot coding
y_train = to_categorical(y_train)

In [ ]:
y_train[9:40]

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0.

In [ ]:
# Test Set
X_test = test_dataset.loc[:, features_cols].values
y_test = test_dataset.loc[:, Label_cols].values

In [ ]:
y_test_onehot = to_categorical(y_test)

In [ ]:
# Create Feedforward model
# Fit the model for the X_train and y_train(one hot coding values)
# Predict teh Y_values from the X_test data
# Initializing the Feedforward Neural Network
model  = Sequential()
# Designing the first hidden layer
model.add(Dense(12, input_dim = X_train.shape[1], activation='sigmoid'))
# Designing the second hidden layer
#model.add(Dense(8, activation='sigmoid'))
# Designing the output layer
model.add(Dense(y_train.shape[1], activation='softmax'))
# Compile the network with the loss function is loss = 'categorical_crossentropy' and optimizer is adam(will update weights)
# metrics model is looking w.r.t accuracy
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
# Fit the model with training and validation data sets
history = model.fit(X_train, y_train,
                    batch_size = 32, epochs = 20,
                    validation_data = (X_test, y_test_onehot))
# Model summary for number of parameters use in the algorithm
model.summary()

Train on 7352 samples, validate on 2947 samples
Epoch 1/20
7352/7352 [==============================] - 2s 266us/step - loss: 1.2912 - acc: 0.5585 - val_loss: 1.0346 - val_acc: 0.7397
Epoch 2/20
7352/7352 [==============================] - 1s 180us/step - loss: 0.8481 - acc: 0.8487 - val_loss: 0.7311 - val_acc: 0.8806
Epoch 3/20
7352/7352 [==============================] - 1s 172us/step - loss: 0.5956 - acc: 0.9076 - val_loss: 0.5424 - val_acc: 0.8884
Epoch 4/20
7352/7352 [==============================] - 1s 171us/step - loss: 0.4354 - acc: 0.9246 - val_loss: 0.4196 - val_acc: 0.9172
Epoch 5/20
7352/7352 [==============================] - 1s 185us/step - loss: 0.3320 - acc: 0.9351 - val_loss: 0.3510 - val_acc: 0.9240
Epoch 6/20
7352/7352 [==============================] - 1s 180us/step - loss: 0.2660 - acc: 0.9471 - val_loss: 0.2884 - val_acc: 0.9372
Epoch 7/20
7352/7352 [==============================] - 1s 178us/step - loss: 0.2222 - acc: 0.9535 - val_loss: 0.2550 - val_acc: 0.9369


In [ ]:
_, accuracy = model.evaluate(X_test, y_test_onehot)
print('Accuracy: %.2f' %(accuracy*100))

2947/2947 [==============================] - 0s 64us/step
Accuracy: 61.83


In [ ]:
y_pred  = model.predict(X_test, batch_size = 64, verbose = 1)
# Converting the one hot coding result to picking the index of max class
y_pred_bool = np.argmax(y_pred, axis = 1)
# Classification result of each class
print(classification_report(y_test, y_pred_bool))

2947/2947 [==============================] - 0s 56us/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       532
           1       0.00      0.00      0.00       491
           2       0.34      1.00      0.51       537
           3       0.99      0.92      0.95       496
           4       0.83      0.96      0.89       420
           5       0.97      0.91      0.94       471

    accuracy                           0.62      2947
   macro avg       0.52      0.63      0.55      2947
weighted avg       0.50      0.62      0.53      2947



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
